SCRIPT_DIR=~/.config/i3/scripts
command=$SCRIPT_DIR/$BLOCK_NAME
separator_block_width=30
color=#FFF766

[load_average]
interval=1
label= 

[disk]
interval=1
label= 
command=if [ $button ]; then thunar; fi; $SCRIPT_DIR/disk

[iface]
interval=10
command=if [ $button ]; then iwgtk; fi; $SCRIPT_DIR/iface

[brightness]
label= 
min_width=60
interval=1

[volume]
command=if [ $button ]; then pavucontrol; fi; $SCRIPT_DIR/volume
interval=1
min_width=60

[packages]
label=
interval=300
command=if [ $button ]; then termite --exec="yay -Syyu"; fi; $SCRIPT_DIR/packages

[battery]
instance=0
interval=5
min_width=60

[date]
command=date '+ %H:%M'
interval=1
label=

[shutdown_menu]
#FG_COLOR=#bbbbbb
#BG_COLOR=#111111
#HLFG_COLOR=#111111
#HLBG_COLOR=#bbbbbb
#BORDER_COLOR=#222222
#ROFI_TEXT=
#ROFI_OPTIONS=-width 11 -location 3 -hide-scrollbar -bw 2
#ZENITY_TITLE=Menu
#ZENITY_TEXT=Action:
#ZENITY_OPTIONS=--column= --hide-header
#ENABLE_CONFIRMATIONS=true
#LAUNCHER=rofi
#LOCKSCRIPT=i3lock --color=${BG_COLOR#"#"}
full_text=   
