#!/bin/bash

MAX_BRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/max_brightness)
CURRENT_BRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/brightness)

let PERC=${CURRENT_BRIGHTNESS}*100/${MAX_BRIGHTNESS}

echo "${PERC}%"

