#!/usr/bin/bash

URGENT_VALUE=25
PACKAGE_COUNT=$(checkupdates+aur &> /dev/null| wc -l)
#PACKAGE_COUNT=1


if [[ "${PACKAGE_COUNT}" -gt 0 ]]; then
  echo " ${PACKAGE_COUNT}"
  if [[ "${PACKAGE_COUNT}" -gt "${URGENT_VALUE}" ]]; then
    exit 33
  fi
fi
