[module/launcher]
type=custom/text
content=""
content-padding = 2
click-left = ~/.config/i3/scripts/launcher.sh
click-right = ~/.config/i3/scripts/settings/color-switch.sh
content-background = ${color.shade1}
content-foreground = ${color.background}

[module/workspaces]
type=internal/i3
pin-workspaces = false
enable-click = true
label-focused = 
label-focused-padding = 1
label-focused-foreground = ${color.background}
label-focused-background = ${color.shade2}

#label-occupied = 
#label-occupied-padding = 1
#label-occupied-foreground = ${color.background}
#label-occupied-background = ${color.shade2}

#label-empty = X
#label-empty-padding = 1
#label-empty-foreground = ${color.background}
#label-empty-background = ${color.shade2}

label-unfocused = %{T4}%{T-}
label-unfocused-padding = 1
label-unfocused-foreground = ${color.background}
label-unfocused-background = ${color.shade2}

label-visible = %{T4}%{T-}
label-visible-padding = 1
label-visible-foreground = ${color.background}
label-visible-background = ${color.shade2}

label-urgent = 
label-urgent-padding = 1
label-urgent-foreground = ${color.background}
label-urgent-background = ${color.shade2}

label-mode-background = ${color.shade2}
label-mode-foreground = ${color.background}
label-mode-padding = 1

format = <label-state><label-mode>

[module/title]
type = internal/xwindow
; Available tags:
;   <label> (default)
format = <label>
format-background = ${color.shade3}
format-foreground = ${color.background}
format-padding = 1

; Available tokens:
;   %title%
; Default: %title%
label =  %title:0:17:...% %{A1:i3-msg kill:}%{A} 

; Used instead of label when there is no window title
; Available tokens:
;   None
label-empty = 

[module/settings]
type = custom/text
content = 
content-padding = 1
content-background = ${color.shade4}
content-foreground = ${color.background}
click-left = ~/.config/i3/scripts/settings/color-switch.sh

[module/cpu]
type = internal/cpu
interval = 2
format =  <label>
label-minlen = 4
format-padding = 1
format-foreground = ${color.background}
format-background = ${color.shade4}

[module/updates]
type = custom/ipc
hook-0 = ~/.config/i3/scripts/packages
format = <output>
format-padding = 1
format-foreground = ${color.background}
format-background = ${color.shade7}
click-left = termite --exec="yay -Syyu" && polybar-msg hook updates 1

[module/updates_trigger]
type=custom/script
exec=polybar-msg hook updates 1
interval=300
label=

[module/onedrive]
type = custom/script
exec = ~/.config/i3/scripts/onedrive
interval = 5
format-foreground = ${color.background}
format-background = ${color.shade6}
format-padding = 1
click-left = thunar ~/OneDrive

[module/backlight]
type = internal/backlight
card = intel_backlight
enable-scroll = true
format =  <label>
format-padding = 1
format-background = ${color.shade5}
format-foreground = ${color.background}
label = %percentage%%
label-minlen = 4

[module/volume]
type = internal/pulseaudio
format-volume = <ramp-volume> <label-volume>
format-volume-padding = 1
format-volume-background = ${color.shade4}
format-volume-foreground = ${color.background}
label-volume-minlen = 4
label-muted =  Muted
label-muted-foreground = ${color.background}
label-muted-background = ${color.shade4}
label-muted-padding = 1
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
click-right = pavucontrol

[module/iface]
type=custom/script
exec=~/.config/i3/scripts/iface
interval=5
click-left=~/.config/i3/scripts/wifi_menu.sh
format-padding = 1
format-background = ${color.shade3}
format-foreground = ${color.background}

[module/battery]
type=internal/battery
format-charging = <animation-charging> <label-charging>
format-charging-padding = 1
format-charging-foreground = ${color.background}
format-charging-background = ${color.shade2}
format-discharging = <ramp-capacity> <label-discharging>
format-discharging-padding = 1
format-discharging-foreground = ${color.background}
format-discharging-background = ${color.shade2}
format-full = <ramp-capacity> <label-full>
format-full-padding = 1
format-full-foreground = ${color.background}
format-full-background = ${color.shade2}
label-charging-minlen = 4
label-discharging-minlen = 4
label-full-minlen = 4
label-charging = %percentage%%
label-discharging = %percentage%%
label-full = %percentage%%
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750


[module/powermenu]
type=custom/text
content = ""
content-padding = 2
click-left = ~/.config/i3/scripts/powermenu.sh
content-background = ${color.shade1}
content-foreground = ${color.background}

[module/time]
type=internal/date
interval = 1.0
time = %H:%M
date = %a %d %b %Y
format = <label>
format-padding = 1
label =  %date%   %time%

[module/dummy]
type=custom/text
content=" "
